name = "ExperienceAnalysis"
uuid = "51cd30ab-a913-41ff-9b6f-9b78880a2ac2"
authors = ["Alec Loudenback <alecloudenback@gmail.com> and contributors"]
version = "2.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "^1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
